# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  project_name: 'demo-pipeline'
  tag: '$(project_name):$(Build.BuildId)'
  imgae_name: '$(project_name)-image'
  config_port: '4000:4000'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Build Docker Image
      inputs:
        targetType: 'inline'
        script: |
          docker build $(Build.SourcesDirectory) -t $(tag)
    - task: Bash@3
      displayName: Save Docker Image
      inputs:
        targetType: 'inline'
        script: |
          docker save $(tag) -o $(Pipeline.Workspace)/$(imgae_name).tar

    - task: CopyFilesOverSSH@0
      displayName: 'Copy file docker image to ec2 '
      inputs:
        sshEndpoint: 'EC2-Demo_Pipeline'
        sourceFolder: '$(Pipeline.Workspace)'
        contents: '*.tar'
    - task: SSH@0
      displayName: 'Run shell inline on remote machine'
      inputs:
        sshEndpoint: 'EC2-Demo_Pipeline'
        runOptions: inline
        inline: |
        sudo docker load -i "$(imgae_name).tar" \
        sudo docker run -p "$(config_port)" -d "$(tag)" \
        sudo rm "$(imgae_name).tar"

