# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  project_name: 'demo-pipeline'
  tag: '$(project_name):$(Build.BuildId)'
  imgae_name: '$(project_name)-image'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Build Docker Image
      inputs:
        targetType: 'inline'
        script: |
          docker build $(Build.SourcesDirectory) -t $(tag)
    - task: Bash@3
      displayName: Save Docker Image
      inputs:
        targetType: 'inline'
        script: |
          docker save $(tag) -o $(Pipeline.Workspace)/$(imgae_name).tar
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/$(imgae_name).tar'
        artifact: '$(project_name)'
        publishLocation: 'pipeline'


    - task: CopyFilesOverSSH@0
      displayName: 'Copy file docker image to ec2 '
      inputs:
        sshEndpoint: 'EC2-Demo_Pipeline'
        sourceFolder: '$(System.DefaultWorkingDirectory)/_00believers00.nest-demo-pipeline/demo-pipeline/$(imgae_name).tar'
        targetFolder: '/home/ubuntu'
        

