trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  project_name: 'demo_pipeline'
  tag: '$(project_name):latest'
  imgae_name: '$(project_name)_image'
  config_port: '4000:4000'

jobs:
  - job: DemoPipelineBackend
    displayName: 'Demo Pipeline Backend'
    steps:
      - template: "build.yml"
      - template: "deploy.yml"